### ISSUE TITLE
Accept AS host address as a cmd param

### ISSUE THREAD

**Issue by dsenim** [ZacSadan/AS_Mysql#8]

**Comment by ZacSadan** [comment]
hi @dsenim , sorry , i removed it because of 
```
zac@aes-nova-staging:~$ python3.7 AS_Mysql/as_mysql.py 
Start server...
Traceback (most recent call last):
  File "AS_Mysql/as_mysql.py", line 22, in <module>
    AS_HOST, HOST, PORT =  os.environ['AS_HOST'] or '127.0.0.1', '', 3306  # default MySQL Server Port
  File "/usr/lib/python3.7/os.py", line 678, in __getitem__
    raise KeyError(key) from None
KeyError: 'AS_HOST'
```

**Comment by dsenim** [comment]
Fixed in GH-13.
